# Generated by Django 5.2.6 on 2025-09-28 12:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hotel_name', models.CharField(max_length=100, verbose_name='Hotel Name')),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Hotel_Images',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.URLField(max_length=500)),
            ],
            options={
                'verbose_name': 'Hotel_Image',
                'verbose_name_plural': 'Hotel_Images',
            },
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('place_name', models.CharField(max_length=100, verbose_name='Place Name')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_user_went', models.BooleanField(default=False)),
                ('went_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Places_images',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('images_url', models.URLField(max_length=500)),
            ],
            options={
                'verbose_name': 'Places_image',
                'verbose_name_plural': 'Places_images',
            },
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_name', models.CharField(max_length=100, verbose_name='Vehicle Name')),
                ('vehicle_number', models.CharField(max_length=100, verbose_name='Vehicle Number')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles_images',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.URLField(max_length=500)),
            ],
            options={
                'verbose_name': 'Vehicles_image',
                'verbose_name_plural': 'Vehicles_images',
            },
        ),
    ]
