# Generated by Django 5.2.6 on 2025-09-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_images',
            field=models.ManyToManyField(blank=True, to='Home.hotel_images'),
        ),
    ]
