# Generated by Django 5.2.6 on 2025-09-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_places_place_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='place_images',
            field=models.ManyToManyField(blank=True, to='Home.places_images'),
        ),
    ]
