# Generated by Django 5.2.6 on 2025-09-28 14:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_alter_places_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
