# Generated by Django 5.2.6 on 2025-09-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_places_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='places_images',
            name='image_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Image Name'),
        ),
    ]
