# Generated by Django 5.2.6 on 2025-09-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_places_images_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='diffuculty_level',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=10),
        ),
        migrations.AddField(
            model_name='places',
            name='region',
            field=models.CharField(choices=[('Aanapurna', 'Aanapurna'), ('Central Nepal', 'Central Nepal'), ('Eastern Nepal', 'Eastern Nepal'), ('Western Nepal', 'Western Nepal'), ('Far Western Nepal', 'Far Western Nepal'), ('Manaslu', 'Manaslu')], default='Null', max_length=20),
        ),
        migrations.AddField(
            model_name='places',
            name='type',
            field=models.CharField(choices=[('Village', 'Village'), ('Town', 'Town'), ('Lake', 'Lake'), ('Plantation', 'Plantation'), ('Trek', 'Trek'), ('Nature', 'Nature')], default='Null', max_length=20),
        ),
    ]
