# Generated by Django 5.2.6 on 2025-09-28 16:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_places_diffuculty_level_places_region_places_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlights',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('highlight', models.CharField(max_length=200, verbose_name='Highlight')),
            ],
        ),
        migrations.AddField(
            model_name='places',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='Booking_Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('number_of_people', models.IntegerField()),
                ('booking_date', models.DateField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.places')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.vehicles')),
            ],
        ),
        migrations.AddField(
            model_name='places',
            name='highlights',
            field=models.ManyToManyField(blank=True, to='Home.highlights'),
        ),
    ]
