# Generated by Django 5.2.6 on 2025-09-28 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_highlights_places_rating_booking_trip_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='places',
            old_name='diffuculty_level',
            new_name='difficulty_level',
        ),
    ]
